<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>New Contact Message</title>
</head>
<body style="margin: 0; padding: 0; font-family: Arial, sans-serif; background-color: #f4f4f4;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f4f4f4; padding: 20px;">
        <tr>
            <td align="center">
                <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
                    <tr>
                        <td style="background-color: #007BFF; padding: 20px; color: white; text-align: center; border-top-left-radius: 8px; border-top-right-radius: 8px;">
                            <h2 style="margin: 0;">New Contact Inquiry</h2>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 30px;">
                            <p style="font-size: 16px;">You have received a new message via your contact form. Here are the details:</p>

                            <table width="100%" cellpadding="0" cellspacing="0" style="margin-top: 20px;">
                                <tr>
                                    <td style="padding: 8px 0;"><strong>Name:</strong></td>
                                    <td style="padding: 8px 0;">{{ $data['name'] }}</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0;"><strong>Email:</strong></td>
                                    <td style="padding: 8px 0;">{{ $data['email'] }}</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0;"><strong>Phone:</strong></td>
                                    <td style="padding: 8px 0;">{{ $data['phone'] }}</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0;"><strong>Subject:</strong></td>
                                    <td style="padding: 8px 0;">{{ $data['subject'] }}</td>
                                </tr>
                                <tr>
                                    <td style="padding: 8px 0; vertical-align: top;"><strong>Message:</strong></td>
                                    <td style="padding: 8px 0;">{{ $data['message'] }}</td>
                                </tr>
                            </table>

                            <p style="margin-top: 30px; font-size: 14px; color: #777;">
                                This email was automatically generated by your website contact form.
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td style="background-color: #f4f4f4; padding: 15px; text-align: center; font-size: 12px; color: #888;">
                            &copy; {{ date('Y') }} {{ env('APP_NAME') }}. All rights reserved.
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
